### PR TITLE
Changed the use of an fixed value to use the correct variable so 'find' ...

### PR DESCRIPTION
**Pull request by tobyontour**
...looks for the VMs in the correct directory (vm_path)

### CODE REVIEW

**Comment by gpkvt** [comment]
Very nice improvements, thanks a lot, and sorry for the late reply.

**Comment by tobyontour** [comment]
Argh, I didn't realise that the pull request would include subsequent commits to my fork. Sorry, I only meant to fix the one variable!

My fork has now moved on even further (and I don't suggest any more merging) and includes a script for starting and stopping the VMs as well as some other tweaks. I apologise for you having to go and fix all the stuff that wasn't finished that I'd committed for my own benefit. At some point I'll take another look at your repo and mine and see if there is anything I can add further that is useful.

**Comment by gpkvt** [comment]
No problem. I'm quite sure there were a way to cherry pick, but I think the makefile, updateip.sh, etc. are quite valuable additons, so it was fully worth the small modifications. 

Also it was my first pull request ever made, so you're very welcome. Looking forward for the next ones. ;)

**Comment by tobyontour** [comment]
I look forward to making them. I'll try and make them less Mac-specific. :-)

**Comment by gpkvt** [comment]
That would be very nice as you seem to have a slightly other (and maybe more modern, less "centralistic") use case than we have, so I think it's very valuable to have both cases covered (+ general MacOS-Support, of course). If you're not sure if some of your modifications/new functions will work with Linux just add a notice to your pull request so I'll take a deeper look and you can focus on the MacOS-Part as I don't have a Mac (at least at work).

**Pull request merged**
